name = "progressive-ai-academy"
compatibility_date = "2025-04-26"

[build]
command = "vite build"

main = "worker/index.ts"

[site]
bucket = "./dist"

[vars]
# Add environment variables here if needed
